# Decomposition papers (Guevara, Aramendia, Heun) meeting notes


## 6 November 2025

### Review of previous action items

- [ ] EA: Get IEA "world indicators" dataset.  Send to Zeus.
- [ ] MKH: Move one function from PFUPipeline2 to new PFUAnalysisTools package.
           Make sure the pipeline still works.
- [ ] ZG: Visualize efficiency results sent by MKH.
- [ ] MKH: Send Final Energy from two countries and two years to Zeus.
           Later, we will be able to send more countries, more years, 
           and useful, and exergy.
- [ ] MKH: Send Zeus examples of allocation and efficiency matrices
           for Ghana and Mexico for same years in Excel files and matsindf format.
- [x] MKH: Send Zeus aggregation file (targeted_aggregations.xlsx)

### Discussion


### New action items



## 22 October 2025

### Review of previous action items

- [x] MKH: Send efficiency information to Zeus in Excel file.
           Just the graphs in table form.
- [ ] EA: Get IEA "world indicators" dataset.  Send to Zeus.
- [ ] MKH: Move one function from PFUPipeline2 to new PFUAnalysisTools package.
           Make sure the pipeline still works.
- [ ] ZG: Visualize efficiency results sent by MKH.
- [ ] MKH: Send Final Energy from two countries and two years to Zeus.
           Later, we will be able to send more countries, more years, 
           and useful, and exergy.

### New action items

- [ ] MKH: Send Zeus examples of allocation and efficiency matrices
           for Ghana and Mexico for same years in Excel files and matsindf format.
- [ ] MKH: Send Zeus aggregation file (targeted_aggregations.xlsx)


## 4 September 2025

### Review of previous action items

- [x] ZG: Look for economic data for the model. 
          Zeus looked a while ago and realized that we need the 
          "world indicators" dataset from the IEA.
- [ ] MKH: Send efficiency information to Zeus in Excel file.
           Just the graphs in table form.
- [x] MKH: Assess steps needed to integrate the new aggregations
           (Renewable electricity, Iron industry (energy)) into 
           the pipeline.
- [x] MKH: Assess modifications to pipeline 
           to use different final energy matrices. 
           Discuss with Emmanuel.

### Discussion

* We discussed next steps and how to move forward 
  on analyses even if it will take MKH a while to 
  move functions from the pipeline into a new PFUAnalysisTools package.

### New action items

- [ ] EA: Get IEA "world indicators" dataset.  Send to Zeus.
- [ ] MKH: Move one function from PFUPipeline2 to new PFUAnalysisTools package.
           Make sure the pipeline still works.
- [ ] ZG: Visualize efficiency results sent by MKH.
- [ ] MKH: Send Final Energy from two countries and two years to Zeus.
           Later, we will be able to send more countries, more years, 
           and useful, and exergy.



## 12 August 2025

### Review of previous action items

- [x] MKH: Fix Statistical differences for all countries
- [x] MKH: Look at efficiencies for all countries
- [ ] ZG: Look for economic data for the model

### Discussion

- Zeus reviewed the graphs
- 80% of graphs are good (stable)
- Didn't see anything very shocking. 
  Most important energy industries are stable.
- There are some structural factors in some graphs
  when some industries started using different technologies
- There are also some IEA differences in reporting and assumptions.
- Things are probably good enough for future work.
- Next steps: Need to push to the useful stage.


### New action items
- [ ] MKH: Send efficiency information to Zeus in Excel file.
           Just the graphs in table form.
- [ ] MKH: Assess steps needed to integrate the new aggregations
           (Renewable electricity, Iron industry (energy)) into 
           the pipeline.
           Discuss with Emmanuel.
- [ ] MKH: Assess modifications to pipeline 
           to use different final energy matrices. 
           Discuss with Emmanuel.
           
           

### Next meeting

- 8 AM EDT, Thur, 28 Aug:  Matt & Emmanuel meet to discuss changes to the pipeline
- 10 AM EDT, Thur, 4 Sept:  All 3 meet to discuss next steps with the pipeline






## 30 July 2025

### Review of previous action items

- [x] MKH: Warn if Statistical differences > other consumption
- [x] MKH: Fix Statistical differences for a few countries: USA, Russia, India, Ghana
- [x] MKH: Look at efficiencies for a few countries; make the .pdf file I made before
- [ ] MKH: Fix Statistical differences for all countries
- [ ] MKH: Look at efficiencies for all countries
- [ ] ZG: Look for economic data for the model

### Discussion

We reviewed the aggregation maps and made a few changes.


### New action items

None.


### Next meeting

11 AM Matt's time Tue 12 Aug 2025




## 30 June 2025

This turned into a check in meeting as
there was no time for progress due to summer travel.

### Next meeting: 11 AM Matt's time, 30 July 2025



## 16 May 2025

### Review of previous action items
- [x] MKH: Implementing higher-level functions in the `IEATools` package.  In progress.
- [x] MKH: Implement algorithms for Statistical differences and Transfers.
           Reallocate only to energy sector in the U_EIOU matrix.

### Status reports
* Matt
    * Finished `IEATools::reallocate_statistical_differences()`
* Zeus
    * Wrote a rough draft of a paper
    
### Next steps for MKH
1. Warn if Statistical differences > other consumption
2. Fix Statistical differences for a few countries: USA, Russia, India, Ghana
3. Look at efficiencies for a few countries; make the .pdf file I made before
4. Fix Statistical differences for all countries
5. Look at efficiencies for all countries

### Next steps for ZG
1. Look for economic data for the model

### Next meeting: 11 AM Matt's time, 30 June 2025



## 11 February 2025

### Review of previous action items
- [ ] MKH: Implementing higher-level functions in the `IEATools` package.  In progress.
- [ ] MKH: Implement algorithms for Statistical differences and Transfers.
           Reallocate only to energy sector in the U_EIOU matrix. In progress.

### Discussion


### Next meeting: 10 AM Matt's time 6 March 2025



## 14 January 2025

### Review of previous action items
- [ ] MKH: Implementing higher-level functions in the `IEATools` package.  In progress.
- [ ] MKH: Implement algorithms for Statistical differences and Transfers.
           Reallocate only to energy sector in the U_EIOU matrix. In progress.
           
### Discussion
* We reviewed MKH's complete algorighm in Excel and decided that would be implemented.

### Next memeting: 10 AM MKH time, Thursday, 30 January 2025



## 17 December 2024


### Discussion
* We worked through the reallocation examples for Stat diffs.
* We will use Option 1 in Matt's spreadsheet.
* No other comments were raised, so Matt can move ahead with implementing the code.

### Next meeting: 11 AM Matt's time 14 Jan 2025.



## 15 November 2024

### Review of previous action items
- [ ] MKH: Implementing higher-level functions in the `IEATools` package.  In progress.
- [x] MKH Add a new way to handle zero data in matsbyname: do nothing.
- [x] MKH Remove `IEATools::reallocate_industry_nes()` from IEATools.
          We now think these allocations are truly Industry but are unspecified.
- [ ] MKH Implement algorithms for Statistical differences and Transfers.
          Reallocate only to energy sector in the U_EIOU matrix.
          
### Discussion
* Algorithm for redistribution of Statistical differences
    * We decided on the following algorithm
        * Reallocate **Y** Stat diffs to the **U** and **Y** matrices.
            * If no other consumption in **U** or **Y**,
              move those specific Stat diffs from **Y** to **R**. (A)
        * Move **R** Stat diffs to the **Y** matrix by subtracting the transpose.
        * Reallocate **Y** Stat diffs to **U** and **Y**
            * If no other consumption in **U** or **Y**,
              move those specific Stat diffs from **Y** to **R**. (A)
            * If any -ve values in **U** or **Y**, 
              move those specific Stat diffs to the **R** matrix. (B)
        * Reallocate any remaining **R** Stat diffs to the **R** and **V** matrices.
    * Note that steps (A) and (B) are repeated in the algorithm and 
      can be moved into a single function.


## 18 Oct 2024

### Review of previous action items
- [x] MKH: Implement lower-level function with argument for how to handle degenerate cases
- [ ] MKH: Implementing higher-level functions in Recca package.  In progress.
- [x] MKH: rename as "reallocate"
- [x] Continue conversation about transfers at next meeting
- [x] ZG: Check the industry (or industries) into which transfers were distributed, 
          especially into U or V matrices? DONE
### MKH: Status of redistribution code
#### Worked on IEATools code and `IEATools::reallocate_industry_nes()`.
* MKH sent questions to ZG.
* We decided to NOT reallocate Industry not elsewhere specified.
* We decided to NOT reallocate Transport not elsewhere specified.
### ZG: Transfers
* Took the easy way.
* Transfers were flows used only in energy sector.
* Transfers were a very small fraction of all energy.
* Flows were used by specific industries.
### New action items
- [ ] MKH Add a new way to handle zero data in matsbyname: do nothing.
- [ ] MKH Remove `IEATools::reallocate_industry_nes()` from IEATools.
          We now think these allocations are truly Industry but are unspecified.
- [ ] MKH Implement algorithms for Statistical differences and Transfers.
          Reallocate only to energy sector in the U_EIOU matrix.
### Next meeting: 11 AM Matt's time on Friday 8 November 2024.


## 27 Sept 2024

### MKH: Status of redistribution code
#### Worked on simple Excel examples to show the theory.
#### Completed draft of `matsbyname::redistribute_byname()`.
#### Should this function be called `matsbyname::reallocate_byname()`? ZG says "yes".
* Works for a single matrix
* Will include RUVY matrices and ECC in Recca package function yet to be written.
### MKH: Discussion of redistribution degenerate cases in file emailed by MKH
#### Example: Non-specified industry energy consumption needs to be redistributed, but no other industries exist.
#### Example: Statistical differences exist, but no other uses of that energy carrier are found.
#### Example: How to distribute statistical differences across U, U_feed, and U_EIOU?
### Next steps
- [ ] MKH: Implement lower-level function with argument for how to handle degenerate cases
- [ ] MKH: Implementing higher-level function in Recca package
- [ ] MKH: rename as "reallocate"
- [ ] Continue conversation about transfers at next meeting
### New action items
- [ ] ZG: Check the industry (or industries) into which transfers were distributed, 
          especially into U or V matrices?
          
### Next meeting: 11 AM MKH time, Friday, 18 October


## 22 Aug 2024

### Discussion of GWh mismatches

* No practical way to separate industries for electricity and heat production
  without studying every country and every year separately.
* Best way to move forward: include the electricity and heat output
  data in the database for people who might want to do focused studies
  on particular countries or years. 
  Make available on the Mexer website.
* Energy balance is correct on IEA data.
  So we need to use that data, not the electricity and heat output.

### Next steps:
- [ ] MKH: Implement code to redistribute statistical differences.
- [ ] MKH: Implement code to redistribute transfers (reallocate to energy sector)
- [ ] MKH: Implement code to redistribute Non-specified (only to Y matrix)
- [ ] MKH: Implement GWhr information into the database.
           Make available to mexer.site.

### Next meeting:
10 AM MKH time (8 AM ZG time, 3 PM EA time), Fri 20 Sept 2024.




## 30 July 2024

### Review of previous action items

- [x] EA: Send code that looked at GWh data to Matt.
- [x] MKH: Build data frames of GWh IEA data.
- [x] MKH: Run new function across GWh data. Look for mismatches.

### Discussion topics
* We looked at how ZG performed balancing of GWh data.
* Didn't find problems with balancing.
* Saw no difference between entering electricity flows.
* Most of the data was exactly the same in the database and the GWh rows.
* EA is now off the hook for disaggregating FF power plants using the GWh data.
  We will disaggregate renewables/nuclear where possible.
  Researchers will aggregate renewables as needed.
  
### Reports from the network
#### EA holiday 5 Aug - 12 Sept 2024


### Next meeting: 

Noon Matt's time, 30 July 2024.  
Teams invitation has been sent.



## 24 July 2024

### Review of previous action items
- [ ] ZG: Review vignette for `LMDIR` package at
          https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 
- [ ] MKH: Build data frames of GWh IEA data.
           Not yet integrated into the CL-PFU pipeline.
- [ ] EA: Implement GWhr information into the database.
          EA found a lot of mismatches between GWh output of electricity 
          and the WEB data.
- [ ] MKH: Implement code to redistribute statistical differences.
- [ ] MKH: Implement code to redistribute transfers (reallocate to energy sector)
- [ ] MKH: Implement code to redistribute Non-specified (only to Y matrix)
- [ ] ZG: Look for old code that uses GWhr data to distribute fossil fuel consumption
          to specialized industries. 
          Send to Emmanuel.
- [ ] ZG: Review vignette for `LMDIR` package at
          https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 
          Half done.
          Checked it once.

### New action items
- [ ] EA: Send ZG a specific year, country, energy carrier example
          that does not balance for the GWh information.
          Denmark, Portugal, UK would be good candidates.
- [ ] ZG: Check data about GWh outputs using EA's suggested 
          year, country, energy carrier. 
          Check for consistency with other output information. 
          

## 12 July 2024

### Review of previous action items
- [x] EA: Create distribution industries for losses.
          Nearly done, but some discussion required.
          Some "Losses" appear and disappear from one year to the next.
          Is this a problem?
          Answer: 
          Yes for a decomposition analysis, but no for the "real" database.
          For the "real" database, add distribution industries
          ONLY when the products with losses exist.
          Do this when the data are still in IEA format
          (not matrix format).
          For the decomposition analysis, 
          we will aggregate many industries and products first.
          So wait until after that aggregation before adding distribution 
          industries. 
          We may unpack matrices and run through same code to 
          form distribution industries, thereafter re-packing the matrices.
- [ ] ZG: Review vignette for `LMDIR` package at
          https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 
          Half done.
          Checked it once.
- [x] EA: Finish distribution industries per discussion above.
- [ ] MKH: Build data frames of GWh IEA data.
- [ ] MKH: Implement code to redistribute statistical differences.
- [ ] MKH: Implement code to redistribute transfers (reallocate to energy sector)
- [ ] MKH: Implement code to redistribute Non-specified (only to Y matrix)
- [ ] EA: Implement GWhr information into the database.
- [ ] ZG: Look for old code that uses GWhr data to distribute fossil fuel consumption
          to specialized industries. 
          Send to Emmanuel.


### Discussion topics

#### Format of GWh data frame

#### Reports from the network

- ZG: He mentioned that soon there will be a database for these studies.
- ZG: If I finish redistributing the rows and columns, we need to re-check the efficiencies.
- EA: Will be starting on a French project in Sept, Oct. 
      Time will probably get squeezed for this decomposition work.
- MKH: Discussed IEA data. Looked at Eviz website.
- ZG: Discharged from half of teaching duties to January.
- ZG: Working with Gabriel Carmona on some material exerguy stuff. 
      ZG has already thought about the format for a database on materials.


### Next meeting 11 AM Matt's time 11 AM Matt's time 24 July 2024



### New action items

None.








## 24 May 2024

### Review of previous action items
- [ ] EA: Create distribution industries for losses.
          Nearly done, but some discussion required.
          Some "Losses" appear and disappear from one year to the next.
          Is this a problem?
          Answer: 
          Yes for a decomposition analysis, but no for the "real" database.
          For the "real" database, add distribution industries
          ONLY when the products with losses exist.
          Do this when the data are still in IEA format
          (not matrix format).
          For the decomposition analysis, 
          we will aggregate many industries and products first.
          So wait until after that aggregation before adding distribution 
          industries. 
          We may unpack matrices and run through same code to 
          form distribution industries, thereafter re-packing the matrices.
- [x] MKH: Develop an Excel example of distributing the products 
           consumed and made by non-physical industries such as
           Statistical differences, Transfers, etc. according 
           to their known consumption and use elsewhere in the ECC.
           This example should be for one country and one year.
           Need to include R+V for fractionizing.
           (And U+Y.)
           Look out for created industries (Manufacture) vs. Resources.
           Order of reallocation:
           (1) Losses (EA algorithm)
           (2) Statistical differences (MKH algorithm, 
               only assign stat diffs to Y matrix, 
               which may result in some -ve values for stat diffs in Y. 
               Distribute the stat diffs across both U and Y.)
               The idea is that consumption is more likely to be wrong.
               Production is more likely to be right.
           (3) Transfers (reallocate to energy sector, MKH algorithm)
           (4) Non-specified (reallocate only to Y matrix, MKH algorithm)
           We reviewed the Excel document called GH1995.xlsx, and 
           all were good with the approach. 
- [ ] ZG: Review vignette for `LMDIR` package at
          https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 


### Discussion topics

#### Use of GWh information to create specific fossil fuel electricity and heat producers. 

See emails of 9 and 10 May 2024 for our offline discussion.

Yes, we can do this.
But need to worry about EIOU (which is not accounted separately).
We can assign EIOU by fraction of output.


### Next meeting

Due to travel, next meeting will be 12 July 2024. 
Teams invitation has been sent.


### New action items
- [ ] EA: Finish distribution industries per discussion above.
- [ ] MKH: Implement code to redistribute statistical differences.
- [ ] MKH: Implement code to redistribute transfers (reallocate to energy sector)
- [ ] MKH: Implement code to redistributed Non-specified (only to Y matrix)
- [ ] EA: Implement GWhr information into the database.
- [ ] ZG: Look for old code that uses GWhr data to distribute fossil fuel consumption to specialized industries.




## 9 May 2024

### New action items
- [ ] EA Create distribution industries for losses.

### Review of previous action items
- [x] EA: Develop an Excel example for simpler distribution industry
          for all products with losses (except Electricity).
          We decided to go for Option 1 
          (specify the source of each product
          with [from XXXX] notation).
          I.e., we will do the same thing we did for Electricity,
          except we'll use a "Distribution" industry instead of Grid.
- [ ] MKH: Develop an Excel example of distributing the products 
           consumed and made by non-physical industries such as
           Statistical differences, Transfers, etc. according 
           to their known consumption and use elsewhere in the ECC.
           This example should be for one country and one year.
           Not done yet.
           Need to include R+V for fractionizing.
           (And U+Y.)
           Look out for created industries (Manufacture) vs. Resources.
           Try another country with more flows (USA).
           Order of reallocation:
           (1) Losses (EA algorithm)
           (2) Statistical differences (MKH algorithm, 
               only assign stat diffs to Y matrix, 
               which may result in some -ve values for stat diffs in Y. 
               Distribute the stat diffs across both U and Y.)
           (3) Transfers (reallocate to energy sector, MKH algorithm)
           (4) Non-specified (reallocate only to Y matrix, MKH algorithm)
- [ ] ZG: Review vignette for `LMDIR` package at
          https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 


## 19 Apr 2024

### New action items
- [ ] EA: Develop an Excel example for simpler distribution industry
          for all products with losses (except Electricity).

### Review of previous action items
- [x] EA: Distribute EIOU for renewable electricity generation by share of
          output.  
          Also did for Nuclear.  
          Coded with arguments to turn the functionality on/off.
- [x] EA: Add a grid industry to the energy conversion chains
          of each country and year.
          Again, has an argument, with default to "off".
- [x] ZG: Review previous work on specifying fossil fuel electricity
          production from Main activity producer electricity plants
          Found his work on Mexico (in Spanish). 
          Confirmed that we will continue with Emmanuel's approach.
          Electricity losses are truly lost and not converted to any type of EIOU.
- [x] MKH: Extract Other Sources and Biosolids and waste
           from R, U, V matrices. Send to ZG.
- [ ] MKH: Develop an Excel example of distributing the products 
           consumed and made by non-physical industries such as
           Statistical differences, Transfers, etc. according 
           to their known consumption and use elsewhere in the ECC.
           This example should be for one country and one year.
- [ ] ZG: Review vignette for `LMDIR` package at
          https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 
          
Next meeting: 10 AM ET, 9 May 2024


## 5 Apr 2024

### New action items
- [ ] EA: Distribute EIOU for renewable electricity generation by share of
          output 
- [ ] EA: Add a grid industry to the energy conversion chains
          of each country and year
- [ ] ZG: Review previous work on specifying fossil fuel electricity
          production from Main activity producer electricity plants
- [ ] MKH: Extract Other Sources and Biosolids and waste
           from R, U, V matrices. Send to ZG.
- [ ] MKH: Develop an Excel example of distributing the products 
           consumed and made by non-physical industries such as
           Statistical differences, Transfers, etc. according 
           to their known consumption and use elsewhere in the ECC.
           This example should be for one country and one year.

### Review of previous action items
- [x] ZG: Put decided aggregations into MKH format. 
          (No longer relevant. We're taking a different approach,
           suggested by Zeus, for distributing 
           Statistical differences, etc. into industries.)
- [ ] ZG: Review vignette for `LMDIR` package at
          https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 
- [x] MKH: Send ZG Non-specified industries (not flows) 
           Industry (not elsewhere specified).

Next meeting: 10 AM (ET), Friday 19 April


## 22 Mar 2024

### New action items
- [ ] MKH: Send ZG Non-specified industries (not flows) Industry
           (not elsewhere specified).

### Review previous action items
- [ ] ZG: Review vignette for `LMDIR` package at
          https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 
- [x] MKH: Make an Excel document with data for 
           Cuba (Biogasoline),
           Austria, Switzerland, Sweden, Turkey, USA 
             (Non-specified primary biofuels and waste). 
           All countries 
             (Manufacture [of Other sources], Other sources, Non-specified, Transfers)
           Send to Zeus.
- [ ] ZG: Put decided aggregations into MKH format.


## 16 February 2024

### Review previous action items

- [x] ZG: Look up Lenzen reference on LMDI and matrices (Brazil)
- [ ] ZG: Review vignette for `LMDIR` package at https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 
- [x] ZG: Add files to GitHub
- [x] MKH: Provide a graph of shares of technologies for each country. Do both sums of V rows and sums of U columns. Make a data frame and send to Zeus for analysis.  Send absolute values to Zeus, not fractions. Data frame will have Country, Year, Industry, matrix, V_row_sum or U_col_sum.


### New action items
- [ ] MKH: Make an Excel document with data for 
           Cuba (Biogasoline),
           Austria, Switzerland, Sweden, Turkey, USA 
             (Non-specified primary biofuels and waste). 
           All countries 
             (Manufacture [of Other sources], Other sources, Non-specified, Transfers)
           Send to Zeus.
- [ ] ZG: Put decided aggregations into MKH format.


## 2 February 2024

- [ ] ZG: Look up Lenzen reference on LMDI and matrices (Brazil)
- [ ] ZG: Review vignette for `LMDIR` package at https://matthewheun.github.io/LMDIR/articles/LMDIR.html. 
- [ ] ZG: Add files to GitHub
- [ ] MKH: Provide a graph of shares of technologies for each country. Do both sums of V rows and sums of U columns. Make a data frame and send to Zeus for analysis.  Send absolute values to Zeus, not fractions. Data frame will have Country, Year, Industry, matrix, V_row_sum or U_col_sum.


### Previous action items:

- [x] ZG: Suggest more aggregations using the new format defined for the pipeline
- [x] ZG: Look through each technology to suggest which ones to aggregate


## 19 January 2024

### Previous action items:

- [x] ZG: Suggest more aggregations using the new format defined for the pipeline
- [x] ZG: Look through each technology to suggest which ones to aggregate

Discussion notes:

* Need to define a criteria for identifying problematic 
  machine efficiencies.
* Then set an alarm to look at those 
  problematic machine efficiencies.
* Need to decide what to do with the impossible trends.
  - Aggregate?
  - Fix?
* Identify countries with most problems, because
  they will become the norm for the rest of the database.
* Possible criteria for problematic efficiencies:
  - Oil refineries: Set max growth or decline from one year to another.
  - Need to check contribution to energy story (percentage) before
    deciding to "fix" or adjust.


## 8 December 2023

### Previous action items:

- [x] MKH: Aggregate Transfers to Oil refineries in ITA for 2000-2008
- [x] MKH: Aggregate Solar, Wind, Hydro, and Geothermal to Renewable electricity for 2015 for all countries
- [x] MKH: Aggregate Coke ovens, Blast furnaces, and Gas works to "Iron industry" for ITA for all years
- [ ] ZG: Suggest more aggregations using the new format defined for the pipeline

Discussion notes:

* Next steps: 
    - Decide objectives of the study, which will help us to decide aggregations.
    - Specify aggregations
    

### New action items:

None.


## 13 October 2023

### Previous action items:

- [x] MKH: Combine "For blended natural gas" and "Natural gas extraction" in every country.
- [x] MKH: Build a system to to enable aggregations in arbitrary countries and years.
- [x] MKH: Write ECC matrices for ITA in 2000 and 2018 to an Excel file
           for inspection at next meeting.
- [x] MKH: Build a file in our GitHub repository to assist with action items. (This file!)

Discussion notes:

* We need to figure out how to deal with Losses
    - Add to U_EIOU (and U)
    - Subtract from V
* We need to figure out how to deal with Transfers.
  Want a algorithm that tells how to deal with lossses
  in a general way.
  
### New action items

- [ ] MKH: Aggregate Transfers to Oil refineries in ITA for 2000-2008
- [ ] MKH: Aggregate Solar, Wind, Hydro, and Geothermal to Renewable electricity for 2015 for all countries
- [ ] MKH: Aggregate Coke ovens, Blast furnaces, and Gas works to "Iron industry" for ITA for all years
- [ ] ZG: Suggest more aggregations using the new format defined for the pipeline


## 22 September 2023

### Previous action items:

- [x] MKH: Create reports of Industry efficiencies. 
           See /OutputData/Reports/IEA eta_i reports folder in Dropbox.
- [x] ZG: Review efficiency data after MKH creates.

### New action items:

- [ ] MKH: Combine "For blended natural gas" and "Natural gas extraction" in every country.
- [ ] MKH: Build a system to to enable aggregations in arbitrary countries and years.
- [ ] MKH: Write ECC matrices for ITA in 2000 and 2018 to an Excel file
           for inspection at next meeting.
- [ ] MKH: Build a file in our GitHub repository to assist with action items. (This file!)


## 8 September 2023

### New action items:

- [ ] MKH: Create reports of Industry efficiencies.
- [ ] ZG: Review efficiency data after MKH creates.
